# Generated by Django 3.2.25 on 2025-06-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('registration_id', models.CharField(blank=True, max_length=100)),
                ('work_start', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('nickName', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.CharField(choices=[('math', 'Matemática'), ('portuguese', 'Português'), ('science', 'Ciências'), ('history', 'História'), ('geography', 'Geografia'), ('physics', 'Física'), ('chemistry', 'Química'), ('biology', 'Biologia'), ('literature', 'Literatura'), ('philosophy', 'Filosofia'), ('sociology', 'Sociologia'), ('english', 'Inglês'), ('arts', 'Artes'), ('music', 'Música'), ('physical_ed', 'Educação Física'), ('psychomotor', 'Psicomotricidade'), ('play', 'Atividades lúdicas'), ('technology', 'Tecnologia')], max_length=100)),
                ('work_shift', models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('night', 'Noite')], max_length=100)),
                ('has_specialization', models.BooleanField(default=False)),
                ('education_level', models.CharField(choices=[('preschool', 'Educação Infantil'), ('elementary_1', 'Ensino Fundamental I'), ('elementary_2', 'Ensino Fundamental II'), ('high_school', 'Ensino Médio')], max_length=100)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.school')),
                ('school_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='school.schoolclass')),
            ],
        ),
    ]
