# Generated by Django 3.2.25 on 2025-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(choices=[('never_studied', 'Nunca estudou'), ('elementary', 'Ensino Fundamental'), ('middle_school', 'Ensino Fundamental II'), ('high_school', 'Ensino Médio'), ('bachelor', 'Graduação'), ('master', 'Mestrado'), ('doctorate', 'Doutorado')], max_length=20)),
                ('relationship_degree', models.CharField(choices=[('father', 'Pai'), ('mother', 'Mãe'), ('guardian', 'Responsável Legal'), ('grandparent', 'Avô/Avó'), ('uncle_aunt', 'Tio/Tia'), ('sibling', 'Irmão/Irmã'), ('other', 'Outro')], max_length=20)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
