# Generated by Django 3.2.25 on 2025-06-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('emoction_id', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('1', 'Linguagem e Comunicação'), ('2', 'Raciocínio e Cognitivo'), ('3', 'Motricidade e Coordenação'), ('4', 'Atividades Sensorial-Exploratórias'), ('5', 'Autonomia e Organização'), ('6', 'Interação e Participação')], max_length=1)),
                ('participation', models.CharField(choices=[('1', 'Não participou'), ('2', 'Parcialmente'), ('3', 'Participou')], max_length=1)),
                ('description', models.CharField(max_length=800)),
                ('student_performance', models.CharField(max_length=800)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('emoction_id', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('objectives', models.JSONField()),
                ('resource', models.JSONField()),
                ('report1', models.TextField()),
                ('report2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('interation', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('concentration', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('autonomy', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('comunication', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('problemSolving', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('compreension', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('regulation', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('respect', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('resistance', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('challenges', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('participation', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
                ('punctuality', models.IntegerField(choices=[('1', 'Não demonstrou'), ('2', 'Parcialmente'), ('3', 'Demonstrou plenamente')])),
            ],
        ),
    ]
