# Generated by Django 3.2.25 on 2025-06-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('preschool', 'Educação Infantil'), ('elementary_1', 'Ensino Fundamental I'), ('elementary_2', 'Ensino Fundamental II'), ('high_school', 'Ensino Médio')], max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('autism_level', models.PositiveIntegerField(choices=[(1, 'Nível 1 - Requer suporte'), (2, 'Nível 2 - Requer suporte substancial'), (3, 'Nível 3 - Requer suporte muito substancial')])),
                ('preferences', models.TextField(blank=True)),
                ('comorbidades', models.TextField(blank=True, default=list)),
                ('triggers_sensitivities', models.TextField(blank=True)),
                ('birthdate', models.DateField()),
                ('support_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('moderate', 'Moderado'), ('high', 'Alto')], max_length=10)),
                ('what_helps_to_calm_down', models.TextField(blank=True)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='parent.parent')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.schoolclass')),
            ],
        ),
    ]
